add feature batch backups

diff --git a/backup-script.template b/backup-script.template
--- a/backup-script.template
+++ b/backup-script.template
@@ -63,8 +63,8 @@ function createBackupDir() {
     fi
   }
   function showError() {
-      echo -e "Cennot create directory ${RED}$1${NC}, because backup job ${RED}\"$BACKUP_NAME\"${NC} doesn't defined as ${RED}$1${NC} backup.."
-      exit 1
+    echo -e "Cennot create directory ${RED}$1${NC}, because backup job ${RED}\"$BACKUP_NAME\"${NC} doesn't defined as ${RED}$1${NC} backup.."
+    exit 1
   }
   if [[ $RETENTION == "yearly" ]]; then
     if [[ $YEARLY != true ]]; then
@@ -245,10 +245,12 @@ if [[ $DB_NAME != "" ]]; then
     databaseSize=$(mysql -h $DB_HOST -e 'SELECT table_schema "DB Name",ROUND(SUM(data_length + index_length)) "DB Size" FROM information_schema.tables GROUP BY table_schema;' | grep -E "(^| )$DB_NAME( |$)" | awk -F "|" '{print $3}' | sed 's/ //g' | numfmt --to=iec)
     if [[ $databaseSize == "" ]]; then
       databaseSize=$(mysql -h $DB_HOST -e 'SELECT table_schema "DB Name",ROUND(SUM(data_length + index_length)) "DB Size" FROM information_schema.tables GROUP BY table_schema;' | egrep "\<$DB_NAME\>" | awk '{print $2}' | sed 's/ //g' | numfmt --to=iec)
+    fi
   else
     databaseSize=$(mysql -h $DB_HOST -u $DB_USERNAME -p"$DB_PASS" -e 'SELECT table_schema "DB Name",ROUND(SUM(data_length + index_length)) "DB Size" FROM information_schema.tables GROUP BY table_schema;' | grep -E "(^| )$DB_NAME( |$)" | awk -F "|" '{print $3}' | sed 's/ //g' | numfmt --to=iec)
     if [[ $databaseSize == "" ]]; then
       databaseSize=$(mysql -h $DB_HOST -u $DB_USERNAME -p"$DB_PASS" -e 'SELECT table_schema "DB Name",ROUND(SUM(data_length + index_length)) "DB Size" FROM information_schema.tables GROUP BY table_schema;' | egrep "\<$DB_NAME\>" | awk '{print $2}' | sed 's/ //g' | numfmt --to=iec)
+    fi
   fi
     
   fi
@@ -347,8 +349,8 @@ function backupDirectory() {
         echo -e "Error backup directory, Cannot find directory ${RED}$DIR_NAME${NC} or directory ${RED}$DIR_NAME${NC} is empty.. "
         telegramNotify "Error backup directory, Cannot find directory $DIR_NAME, or directory $DIR_NAME is empty.."
       else
-        echo -e "Cannot backup Directory ${RED}$DIR_NAME${NC}, not enough disk space..\nRoot Size: $rootSize.\nDatabase Size: $databaseSize."
-        telegramNotify "Cannot backup Database ${RED}$DIR_NAME${NC}, not enough disk space..
+        echo -e "Cannot backup Directory ${RED}$DIR_NAME${NC}, not enough disk space..\nRoot Size: $rootSize.\nDirectory Size: $path_dirSize."
+        telegramNotify "Cannot backup Directory ${RED}$DIR_NAME${NC}, not enough disk space..
 Root Size: $rootSize.
 Directory Size: $path_dirSize."
       fi
