done create feature merge dump and archive mysql database

diff --git a/backup-script.template b/backup-script.template
--- a/backup-script.template
+++ b/backup-script.template
@@ -41,13 +41,23 @@ RETENTION=$1
 ## VARIABLES
 
 # Backup Directory
-BACKUP_DIR="$BASE_DIR/backups/$BACKUP_NAME"
+if [[ $BATCH == true ]]; then
+  BACKUP_NAME_BATCH=$(echo $BACKUP_NAME | awk -F "-" '{print $1}')
+  BACKUP_NAME_NEW=$BACKUP_NAME_BATCH
+  BACKUP_NAME_NEW=$(echo $BACKUP_NAME_NEW | sed -e 's/\-/\\\-/g' -e 's/\_/\\\_/g')
+  BACKUP_NAME=$(echo $BACKUP_NAME | sed -e 's/'$BACKUP_NAME_NEW'//' -e 's/\-//')
+  BACKUP_DIR="$BASE_DIR/backups/$BACKUP_NAME_BATCH/$BACKUP_NAME"
+  NEXTCLOUD_PATH_DB="$NEXTCLOUD_PATH_DB/$BACKUP_NAME"
+  NEXTCLOUD_PATH_DIR="$NEXTCLOUD_PATH_DIR/$BACKUP_NAME"
+else
+  BACKUP_DIR="$BASE_DIR/backups/$BACKUP_NAME"
+fi
 
 function createBackupDir() {
   function mkdirRetention() {
     if [[ ! -d $BACKUP_DIR/$1 ]]; then
       if ! mkdir $BACKUP_DIR/$1; then
-        echo -e "Error whle creating ${RED}$1${NC} directory.."
+        echo -e "Error while creating ${RED}$1${NC} directory.."
         exit 1
       fi
     fi
@@ -111,6 +121,9 @@ function actionAtNextcloud() {
 function createDirInNextcloud() {
   if [[ $NEXTCLOUD_PATH_DIR != "" ]]; then
     for i in {1..5} ; do
+      if [[ $BATCH == true ]]; then
+        actionAtNextcloud MKCOL $NEXTCLOUD_PATH_DIR
+      fi
       actionAtNextcloud MKCOL $NEXTCLOUD_PATH_DIR $1
       if cat /tmp/upcli-output | grep -q "already exists" || cat $BACKUP_DIR/nextcloud-log | head -n 1 |grep -q "HTTP/2 201" ; then
         NEXTCLOUD_PATH_DIR_DONE=true
@@ -124,6 +137,9 @@ Please read log at $BACKUP_DIR/log"
   fi
   if [[ $NEXTCLOUD_PATH_DB != "" ]]; then
     for i in {1..5} ; do
+      if [[ $BATCH == true ]]; then
+        actionAtNextcloud MKCOL $NEXTCLOUD_PATH_DB
+      fi
       actionAtNextcloud MKCOL $NEXTCLOUD_PATH_DB $1;
       if cat /tmp/upcli-output | grep -q "already exists" || cat $BACKUP_DIR/nextcloud-log | head -n 1 |grep -q "HTTP/2 201" ; then
         NEXTCLOUD_PATH_DB_DONE=true
@@ -159,8 +175,8 @@ if [[ $1 == "daily" ]]; then
 fi
 
 function uploadToNextcloud () {
-  curl -T $BACKUP_DIR/$1-$time.tar.gz -u $NEXTCLOUD_USERNAME:$NEXTCLOUD_PASS "https://$NEXTCLOUD_HOST/remote.php/dav/files/$NEXTCLOUD_USERNAME/$2/$1-$time.tar.gz" | tee $BACKUP_DIR/log &> /tmp/upcli-output 
-  actionAtNextcloud PROPFIND $2 $1-$time.tar.gz;
+  curl -T $BACKUP_DIR/$1 -u $NEXTCLOUD_USERNAME:$NEXTCLOUD_PASS "https://$NEXTCLOUD_HOST/remote.php/dav/files/$NEXTCLOUD_USERNAME/$2/$1" | tee $BACKUP_DIR/log &> /tmp/upcli-output 
+  actionAtNextcloud PROPFIND $2 $1;
 }
 
 function checkIfCapacityIsEnough(){
@@ -187,17 +203,46 @@ else
 fi
 }
 
+function deleteLocalBackup() {
+  
+  if [[ $NEXTCLOUD_USERNAME != "" ]] && [[ $NEXTCLOUD_PASS != "" ]]; then
+    getBak=$(ls $BACKUP_DIR | grep $time)
+  else
+    date=$(date --date="yesterday" +"%F")
+    getBak=$(ls $BACKUP_DIR | grep $date)
+  fi
+
+  if [[ $getBak != "" ]]; then
+    for file in ${getBak[@]} ; do
+      if rm $BACKUP_DIR/$file; then
+        echo ""
+        if [[ $NEXTCLOUD_USERNAME != "" ]] && [[ $NEXTCLOUD_PASS != "" ]]; then
+          echo "Success delete local backup: $file"
+        else
+          echo "Success delete yesterday's backup: $file"
+        fi
+      fi
+    done
+  fi
+
+}
+
+
 # DATABASE
 if [[ $DB_NAME != "" ]]; then
 
-  databaseSize=$(docker exec -it bc90a3aba97a mysql -u root -p"root" -e 'SELECT table_schema "DB Name",ROUND(SUM(data_length + index_length)) "DB Size" FROM information_schema.tables GROUP BY table_schema;' | grep $DB_NAME | awk -F "|" '{print $3}' | sed 's/ //g' | numfmt --to=iec)
+  databaseSize=$(mysql -h $DB_HOST -u root -p"root" -e 'SELECT table_schema "DB Name",ROUND(SUM(data_length + index_length)) "DB Size" FROM information_schema.tables GROUP BY table_schema;' | grep -E "(^| )$DB_NAME( |$)" | awk -F "|" '{print $3}' | sed 's/ //g' | numfmt --to=iec)
+  if [[ $databaseSize == "" ]]; then
+    databaseSize=$(mysql -h $DB_HOST -u root -p"root" -e 'SELECT table_schema "DB Name",ROUND(SUM(data_length + index_length)) "DB Size" FROM information_schema.tables GROUP BY table_schema;' | egrep "\<$DB_NAME\>" | awk '{print $2}' | sed 's/ //g' | numfmt --to=iec)
+    
+  fi
   databaseSizeLetter=$(echo ${databaseSize: -1})
   databaseSizeNoLetter=$(echo $databaseSize | sed 's/.$//')
 
   if ! checkIfCapacityIsEnough $databaseSizeNoLetter $databaseSizeLetter; then
     if [[ $databaseSize == "" ]]; then
       echo -e "Error backup database, Cannot find database ${RED}$DB_NAME${NC} or database ${RED}$DB_NAME${NC} is empty.. "
-      telegramNotify "Error backup database, Cannot find database $DB_NAME, or database $DB_NAME is empty.."
+      telegramNotify "Service database error or database $DB_NAME is empty, please do manual troubleshoot.."
     else
       echo -e "Cannot backup Database ${RED}$DB_NAME${NC}, not enough disk space..\nRoot Size: $rootSize.\nDatabase Size: $databaseSize."
       telegramNotify "Cannot backup Database $DB_NAME, not enough disk space..
@@ -209,70 +254,92 @@ Database Size: $databaseSize."
 
     echo -e "Dumping database ${GREEN}$DB_NAME${NC}.."
     if [[ $NO_DB_CREDS == true ]]; then
-      mysqldump -h $DB_HOST $DB_NAME &> $BACKUP_DIR/$DB_NAME.sql 
-    else
-      mysqldump -h $DB_HOST -u $DB_USERNAME -p"$DB_PASS" $DB_NAME &> $BACKUP_DIR/$DB_NAME.sql 
-    fi
-    if ! cat $BACKUP_DIR/$DB_NAME.sql | head -n 1 | grep "error"; then
-      echo -e "Success dump database ${GREEN}$DB_NAME${NC}..";
-      echo 'Archiving..';
-      cd $BACKUP_DIR;
-      if tar -czvf $BACKUP_DIR/$DB_NAME-$time.tar.gz $DB_NAME.sql | tee -a $BACKUP_DIR/log; then
-        rm $BACKUP_DIR/$DB_NAME.sql
-        echo 'Database archived..';
-        DB_DONE=true
-
-      end=$(date +%s)
-
-      echo 'Elapsed time '$((end-start))' seconds..'
-
-    else
-
-      echo -e "Failed archiving database ${RED}$DB_NAME${NC}..";
-      telegramNotify "Failed archivng database $DB_NAME..
-Please read log at $BACKUP_DIR/log"
-      exit 1
-      fi
-
-    else
-
-      echo -e "Failed dump database ${RED}$DB_NAME${NC}..";
-      telegramNotify "Failed dump database $DB_NAME..
+      if mysqldump -h $DB_HOST $DB_NAME | gzip -c &> $BACKUP_DIR/$DB_NAME-$time.sql.gz; then
+        echo -e "Success dump database ${GREEN}$DB_NAME${NC}..";
+        DUMP_DONE=true
+      else
+        echo -e "Failed dump database ${RED}$DB_NAME${NC}..";
+        telegramNotify "Failed dump database $DB_NAME..
 Please read log at $BACKUP_DIR/log
 or you can see output of $BACKUP_DIR/$DB_NAME.sql file..
-      "
-      exit 1
-
+"
+      fi
+    else
+      if mysqldump -h $DB_HOST -u $DB_USERNAME -p"$DB_PASS" $DB_NAME | gzip -c &> $BACKUP_DIR/$DB_NAME-$time.sql.gz; then
+        echo -e "Success dump database ${GREEN}$DB_NAME${NC}..";
+        DUMP_DONE=true
+      else
+        echo -e "Failed dump database ${RED}$DB_NAME${NC}..";
+        telegramNotify "Failed dump database $DB_NAME..
+Please read log at $BACKUP_DIR/log
+or you can see output of $BACKUP_DIR/$DB_NAME.sql file..
+"
+      fi
     fi
+    # if ! cat $BACKUP_DIR/$DB_NAME-$time.sql.gz | head -n 1 | grep "error"; then
+    #   echo -e "Success dump database ${GREEN}$DB_NAME${NC}..";
+  #     echo 'Archiving..';
+  #     cd $BACKUP_DIR;
+  #     if tar -czvf $BACKUP_DIR/$DB_NAME-$time.tar.gz $DB_NAME.sql | tee -a $BACKUP_DIR/log; then
+  #       rm $BACKUP_DIR/$DB_NAME.sql
+  #       echo 'Database archived..';
+  #       DB_DONE=true
+  #
+  #       end=$(date +%s)
+  #
+  #       echo 'Elapsed time '$((end-start))' seconds..'
+  #
+  #     else
+  #
+  #       echo -e "Failed archiving database ${RED}$DB_NAME${NC}..";
+  #       telegramNotify "Failed archivng database $DB_NAME..
+  # Please read log at $BACKUP_DIR/log"
+  #       exit 1
+  #     fi
+
+#     else
+#
+#       echo -e "Failed dump database ${RED}$DB_NAME${NC}..";
+#       telegramNotify "Failed dump database $DB_NAME..
+# Please read log at $BACKUP_DIR/log
+# or you can see output of $BACKUP_DIR/$DB_NAME.sql file..
+#       "
+#       exit 1
+#
+#     fi
 
   # Upload To Nextcloud
 
   start=$(date +%s)
 
-  # DATABASE
+  if [[ $DUMP_DONE == true ]]; then
+    
+    echo "Uploading to Nextcloud.."
 
-  echo "Uploading to Nextcloud.."
+    if [[ $NEXTCLOUD_USERNAME != "" ]] && [[ $NEXTCLOUD_PASS != "" ]]; then
+      for i in {1..5} ; do
+        uploadToNextcloud "$DB_NAME-$time.sql.gz" "$NEXTCLOUD_PATH_DB/$1";
 
-  if [[ $NEXTCLOUD_USERNAME != "" ]] && [[ $NEXTCLOUD_PASS != "" ]]; then
-    for i in {1..5} ; do
-      uploadToNextcloud $DB_NAME "$NEXTCLOUD_PATH_DB/$1";
+        if cat /tmp/upcli-output | grep -q "200 OK"; then
+          break
+        fi
+      done
 
-      if cat /tmp/upcli-output | grep -q "200 OK"; then
-        break
+      if ! cat /tmp/upcli-output | grep -q "200 OK"; then
+        echo -e "Failed upload database ${RED}$DB_NAME${NC} to Nextcloud.."
+        echo 'Elapsed time '$((end-start))' seconds..'
+        telegramNotify "Failed upload database $DB_NAME to Nextcloud..
+        Please read log at $BACKUP_DIR/log"
+        exit 1
+      else
+        echo ""
+        echo -e "Success upload database ${GREEN}$DB_NAME${NC} to Nextcloud"
+        UPLOAD_DATABASE=true
       fi
-    done
-
-    if ! cat /tmp/upcli-output | grep -q "200 OK"; then
-      echo -e "Failed upload database ${RED}$DB_NAME${NC} to Nextcloud.."
-      echo 'Elapsed time '$((end-start))' seconds..'
-      telegramNotify "Failed upload database $DB_NAME to Nextcloud..
-Please read log at $BACKUP_DIR/log"
-      exit 1
-    else
-      echo ""
-      echo -e "Success upload database ${GREEN}$DB_NAME${NC} to Nextcloud"
-      UPLOAD_DATABASE=true
     fi
+
+    deleteLocalBackup;
+
   fi
 
   end=$(date +%s)
@@ -315,7 +382,7 @@ Please read log at $BACKUP_DIR/log"
       # Nextcloud
       if [[ $NEXTCLOUD_USERNAME != "" ]] && [[ $NEXTCLOUD_PASS != "" ]]; then
         for i in {1..5} ; do
-          uploadToNextcloud $DIR_NAME "$NEXTCLOUD_PATH_DIR/$1";
+          uploadToNextcloud "$DIR_NAME-$time.tar.gz" "$NEXTCLOUD_PATH_DIR/$RETENTION";
 
           if cat /tmp/upcli-output | grep -q "200 OK"; then
             break
@@ -331,6 +398,9 @@ Please read log at $BACKUP_DIR/log"
         else
           echo ""
           echo -e "Success upload directory ${GREEN}$DIR_NAME${NC} to Nextcloud"
+
+          deleteLocalBackup;
+
           return 0
         fi
       fi
@@ -405,27 +475,6 @@ Please read log at $BACKUP_DIR/log"
     fi
   fi
 }
-
-if [[ $NEXTCLOUD_USERNAME != "" ]] && [[ $NEXTCLOUD_PASS != "" ]]; then
-  getBak=$(ls $BACKUP_DIR | grep $time)
-else
-  date=$(date --date="yesterday" +"%F")
-  getBak=$(ls $BACKUP_DIR | grep $date)
-fi
-
-if [[ $getBak != "" ]]; then
-  for file in ${getBak[@]} ; do
-    if rm $BACKUP_DIR/$file; then
-      echo ""
-      if [[ $NEXTCLOUD_USERNAME != "" ]] && [[ $NEXTCLOUD_PASS != "" ]]; then
-        echo "Success delete local backup: $file"
-      else
-        echo "Success delete yesterday's backup: $file"
-      fi
-    fi
-  done
-fi
-
 
 # Delete backup retention in nextcloud
 if [[ $NEXTCLOUD_USERNAME != "" ]] && [[ $NEXTCLOUD_PASS != "" ]]; then
