fix backup name for batch backup

diff --git a/upcli b/upcli
--- a/upcli
+++ b/upcli
@@ -471,7 +471,7 @@ while (( "$#" )); do
       shift 
       ;;
     -v|--version)
-      echo "Upcli version 0.1.2-beta"
+      echo "Upcli version 0.1.3-beta"
       exit 0
       shift 
       ;;
@@ -506,9 +506,8 @@ function insertBackupName() {
   if [[ $BACKUP_NAME == "" ]]; then
     echo "----------------------------------------------------------------"
     echo "| Insert backup name, cannot have space or special characters. |"
-    echo "| you can use - or _ for separator.                            |"
-    echo "| example: test                                                |"
-    echo "| example: test-backup1                                        |"
+    echo "| you can use _ for separator.                                 |"
+    echo "| example: test1                                               |"
     echo "| example: myfirst_website                                     |"
     echo "----------------------------------------------------------------"
 
@@ -517,7 +516,7 @@ function insertBackupName() {
       read -p "Backup Name: " BACKUP_NAME
       ((i++))
       if [[ $BACKUP_NAME != "" ]]; then
-        if echo $BACKUP_NAME | egrep -e "^[a-zA-Z0-9_-]*$" > /tmp/upcli-output; then
+        if echo $BACKUP_NAME | egrep -e "^[a-zA-Z0-9_]*$" > /tmp/upcli-output; then
           break
         else
           echo "--------------------------------------"
@@ -1421,19 +1420,6 @@ fi
 function upcli() {
 for u in {1..5}; do
 
-  if [[ $QUIET == true ]]; then
-    if [[ $BACKUP_NAME == "" ]]; then
-      echo "---------------------------------"
-      echo -e "| ${RED}ERROR!${NC}                        |"
-      echo "| you must insert backup name.. |"
-      echo "| exiting..                     |"
-      echo "---------------------------------"
-      exit 1
-    fi
-  else
-    insertBackupName;
-  fi
-
   # Check if backup name uniq
   if [[ -f $BASE_DIR/backup-list ]]; then
     if cat $BASE_DIR/backup-list | awk -F "|" '{print $1}' | grep -E "(^| )$BACKUP_NAME( |$)"  > /tmp/upcli-output; then
@@ -2122,8 +2108,33 @@ fi
 ## END FUNCTION UPCLI
 }
 
+if [[ $QUIET == true ]]; then
+  if [[ $BACKUP_NAME == "" ]]; then
+    echo "---------------------------------"
+    echo -e "| ${RED}ERROR!${NC}                        |"
+    echo "| you must insert backup name.. |"
+    echo "| exiting..                     |"
+    echo "---------------------------------"
+    exit 1
+  else
+    if echo $BACKUP_NAME | egrep -e "^[a-zA-Z0-9_]*$" > /tmp/upcli-output; then
+      :
+    else
+      echo $BACKUP_NAME
+      echo "------------------------------------------------------"
+      echo -e "| ${RED}ERROR!${NC}                                             |"
+      echo "| you cannot use special character for backup name.. |"
+      echo "| please retry                                       |"
+      echo "------------------------------------------------------"
+      exit 1
+    fi
+  fi
+else
+  insertBackupName;
+fi
+
 if [[ $BATCH == true ]]; then
-  BACKUP_NAMES=($(ls /home))
+  BACKUP_NAMES=($(ls /home/ug/home))
   for b in ${BACKUP_NAMES[@]}
   do
 
@@ -2138,7 +2149,7 @@ if [[ $BATCH == true ]]; then
     unset PATH_DIR;
     PATH_DIR=()
     for d in ${BATCH_PATH_DIR[@]} ; do
-      PATH_DIR+=("/home/$b/$d")
+      PATH_DIR+=("/home/ug/home/$b/$d")
     done
     upcli;
     echo ""
@@ -2148,6 +2159,7 @@ if [[ $BATCH == true ]]; then
 else
   upcli;
 fi
+
 
 echo "-------------"
 echo -e "| ${GREEN}Success${NC}.. |" 
